mdd-seo-stacked-272382-272385
IgniteUI/igniteui-blazor-examples pull request #110
Opened 2021-02-17 22:05 UTC by mddifilippo89

seo - 272382-272385

Stacked:
Spline
SplineArea
Line
Area

2021-02-22 21:18 UTC, HUSSAR-mtrela requested changes

2021-02-22 21:18 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/stacked-area-chart/App.razor
> +﻿@page "/StackedAreaChart"
remove this line

2021-02-22 21:18 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/stacked-line-chart/App.razor
> +﻿@page "/StackedLineChart"
remove this line

2021-02-22 21:18 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/stacked-spline-area-chart/App.razor
> +﻿@page "/StackedSplineAreaChart"
remove this line

2021-02-22 21:18 UTC, HUSSAR-mtrela commented on samples/charts/data-chart/stacked-spline-chart/App.razor
> +﻿@page "/StackedSplineChart"
remove this line

2021-02-23 18:12 UTC, mddifilippo89 commented on samples/charts/data-chart/stacked-area-chart/App.razor
> +﻿@page "/StackedAreaChart"
resolved, pending

2021-02-23 18:12 UTC, mddifilippo89 commented on samples/charts/data-chart/stacked-line-chart/App.razor
> +﻿@page "/StackedLineChart"
resolved, pending

2021-02-23 18:12 UTC, mddifilippo89 commented on samples/charts/data-chart/stacked-spline-area-chart/App.razor
> +﻿@page "/StackedSplineAreaChart"
resolved, pending

2021-02-23 18:12 UTC, mddifilippo89 commented on samples/charts/data-chart/stacked-spline-chart/App.razor
> +﻿@page "/StackedSplineChart"
resolved, pending

2021-02-23 19:01 UTC, HUSSAR-mtrela approved these changes

2021-02-23 19:01 UTC, merged