Add Column Hiding Toolbar Style sample
IgniteUI/igniteui-blazor-examples pull request #393
Opened 2023-05-18 06:54 UTC by skrustev

2023-05-18 11:26 UTC, MayaKirova approved these changes

2023-07-06 17:34 UTC, HUSSAR-mtrela requested changes

2023-07-06 17:34 UTC, HUSSAR-mtrela commented on samples/grids/grid/column-hiding-toolbar-style/App.razor
> +        --igx-column-actions-title-color: #ffcd0f;
shouldn't this sample use --igc prefixes instead of --igx prefixes?

2023-07-10 19:45 UTC, skrustev commented
Closing this since this is now ported to xplat-examples: 
https://github.com/IgniteUI/igniteui-xplat-examples/pull/262

2023-07-10 19:45 UTC, closed without merging