chore(*): update ig to 23.2.241
IgniteUI/igniteui-blazor-examples pull request #751
Opened 2024-06-18 19:55 UTC by dkamburov

2024-06-19 07:21 UTC, MayaKirova approved these changes

2024-06-20 15:37 UTC, HUSSAR-mtrela requested changes
@ChronosSF @dkamburov this PR fails because it uses 23.2.241 package which is not published yet on proget.
https://packages.infragistics.com/packages?FeedId=2&Count=500
Please either undo that change in pipeline YML files or publish that package to proget.

2024-06-21 19:55 UTC, HUSSAR-mtrela commented
@dkamburov this error occurs in pivot-grid sample:

\grids\pivot-grid\features\App.razor(60,17): Error CS0272: The property or indexer 'IgbPivotConfiguration.Columns' cannot be used in this context because the set accessor is inaccessible

2024-06-24 07:07 UTC, dkamburov commented
@HUSSAR-mtrela yeah, it's a sample generation issue, hope to get that fixed with https://infragistics.visualstudio.com/NetAdvantage/_git/dev-tools/pullrequest/13039

2024-06-28 11:57 UTC, closed without merging